name: Terraform Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          cd day-1Terraform-basic-configure
          terraform init

      - name: Terraform Plan
        run: |
          cd day-1Terraform-basic-configure
          terraform plan

      - name: Terraform Apply
        run: |
          cd day-1Terraform-basic-configure
          terraform apply -auto-approve
